### ISSUE TITLE
No module named 'pymarkdown'

### ISSUE THREAD

**Issue by HowieG** [crewAIInc/crewAI-examples#102]
crewAI-examples/markdown_validator/main.py", line 7, in <module>
    from pymarkdown.api import PyMarkdownApi, PyMarkdownApiException
ModuleNotFoundError: No module named 'pymarkdown'

**Comment by lifeisegg2k** [comment]
same thing error
```sh
╰─❯ python main.py README.md
/Users/tester/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/Users/tester/work/nomad/crewAI-examples/markdown_validator/main.py", line 8, in <module>
    from MarkdownTools import markdown_validation_tool
  File "/Users/tester/work/nomad/crewAI-examples/markdown_validator/MarkdownTools.py", line 5, in <module>
    from pymarkdown.api import PyMarkdownApi, PyMarkdownApiException
  File "/Users/tester/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pymarkdown/__init__.py", line 1, in <module>
    from .core import process
  File "/Users/tester/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pymarkdown/core.py", line 4, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by sourangshupal** [comment]
from pymarkdown.api import PyMarkdownApi, PyMarkdownApiException
ModuleNotFoundError: No module named 'pymarkdown'
