### ISSUE TITLE
game-builder-crew Task expected_output error

### ISSUE THREAD

**Issue by kaurov** [crewAIInc/crewAI-examples#116]
1) how to fix the following error message?
>/crewAI-examples/game-builder-crew$ python main.py

```
Traceback (most recent call last):
  File "/crewAI-examples/game-builder-crew/main.py", line 22, in <module>
    code_game = tasks.code_task(senior_engineer_agent, game)
  File "/crewAI-examples/game-builder-crew/tasks.py", line 6, in code_task
    return Task(description=dedent(f"""You will create a game using python, these are the instructions:
  File "/home/username/.local/lib/python3.10/site-packages/crewai/task.py", line 76, in __init__
    super().__init__(**config, **data)
  File "/home/username/.local/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Task
expected_output
  Field required [type=missing, input_value={'description': "You will...o
produce perfect code)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

```

2) https://github.com/joaomdmoura/crewAI-examples/tree/main/game-builder-crew/README.md
please replace 'landing page' by 'game'

**Comment by daffainfo** [comment]
@kaurov add `expected_output` attribute when creating a task, for example:
```
Task(
        description="Example",
        agent=general_agent,
        expected_output="Example"
)
```

**Comment by dashan996** [comment]
Anyone can help? Why if set "allow_delegation=True",  chief agent always stop due to reach limitation?  But false is ok . I use llama3.  Thanks a lot!
