### ISSUE TITLE
Command "crewai run" not working on write_a_book_with_flows

### ISSUE THREAD

**Issue by bluehose54** [crewAIInc/crewAI-examples#176]
I have cloned the  write_a_book_with_flows project and added my .env to the root directory and every time I use crewai run it give me an error that says 

Command not found: run_crew
An error occurred while running the crew: Command '['poetry', 'run', 'run_crew']' returned non-zero exit status 1.

Has anyone else had this error and resolved it?

I have double checked and I do have crewai installed, activated my environment, and added the interpreter path.

**Comment by 0xhiroki** [comment]
@bluehose54 I've encountered the same issue, but following the instruction on how to run a flow did the trick. Make sure to follow the instruction here [for how to run a flow](https://docs.crewai.com/concepts/flows#running-the-flow).

**Comment by miaohf** [comment]
It seems that Ollama is currently not supported in this example.


`crewai flow run
Running the Flow
/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/src/write_a_book_with_flows/crews/write_book_chapter_crew/write_book_chapter_crew.py:17: LangChainDeprecationWarning: The class `Ollama` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaLLM``.
  llm = Ollama(
Kickoff the Book Outline Crew

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,210 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,211 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,217 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,218 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,225 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,226 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,228 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable
# Agent: Research Agent
## Task: Research the provided topic of Exploring the latest trends in AI across different industries as of September 2024 to gather the most important information that will  be useful in creating a book outline. Ensure you focus on high-quality, reliable sources.
Here is some additional information about the author's desired goal for the book:\n\n 
        The goal of this book is to provide a comprehensive overview of the current state of artificial intelligence in September 2024.
        It will delve into the latest trends impacting various industries, analyze significant advancements,
        and discuss potential future developments. The book aims to inform readers about cutting-edge AI technologies
        and prepare them for upcoming innovations in the field.
    

2024-10-19 18:03:06,253 - 139744543886208 - llm.py-llm:161 - ERROR: LiteLLM call failed: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=Ollama
Params: {'model': 'llama3.2', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': None, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, 'raw': None}
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,256 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable
# Agent: Research Agent
## Task: Research the provided topic of Exploring the latest trends in AI across different industries as of September 2024 to gather the most important information that will  be useful in creating a book outline. Ensure you focus on high-quality, reliable sources.
Here is some additional information about the author's desired goal for the book:\n\n 
        The goal of this book is to provide a comprehensive overview of the current state of artificial intelligence in September 2024.
        It will delve into the latest trends impacting various industries, analyze significant advancements,
        and discuss potential future developments. The book aims to inform readers about cutting-edge AI technologies
        and prepare them for upcoming innovations in the field.
    

2024-10-19 18:03:06,276 - 139744543886208 - llm.py-llm:161 - ERROR: LiteLLM call failed: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=Ollama
Params: {'model': 'llama3.2', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': None, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, 'raw': None}
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

Provider List: https://docs.litellm.ai/docs/providers

2024-10-19 18:03:06,279 - 139744543886208 - llm.py-llm:178 - ERROR: Failed to get supported params: argument of type 'NoneType' is not iterable
# Agent: Research Agent
## Task: Research the provided topic of Exploring the latest trends in AI across different industries as of September 2024 to gather the most important information that will  be useful in creating a book outline. Ensure you focus on high-quality, reliable sources.
Here is some additional information about the author's desired goal for the book:\n\n 
        The goal of this book is to provide a comprehensive overview of the current state of artificial intelligence in September 2024.
        It will delve into the latest trends impacting various industries, analyze significant advancements,
        and discuss potential future developments. The book aims to inform readers about cutting-edge AI technologies
        and prepare them for upcoming innovations in the field.
    

2024-10-19 18:03:06,308 - 139744543886208 - llm.py-llm:161 - ERROR: LiteLLM call failed: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=Ollama
Params: {'model': 'llama3.2', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': None, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, 'raw': None}
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
Traceback (most recent call last):
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agent.py", line 228, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 93, in invoke
    formatted_answer = self._invoke_loop()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 175, in _invoke_loop
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 115, in _invoke_loop
    answer = self.llm.call(
             ^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/llm.py", line 155, in call
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1007, in wrapper
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/utils.py", line 897, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/main.py", line 2994, in completion
    raise exception_type(
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/main.py", line 891, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 520, in get_llm_provider
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 497, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=Ollama
Params: {'model': 'llama3.2', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': None, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, 'raw': None}
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agent.py", line 228, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 93, in invoke
    formatted_answer = self._invoke_loop()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 175, in _invoke_loop
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 115, in _invoke_loop
    answer = self.llm.call(
             ^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/llm.py", line 155, in call
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1007, in wrapper
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/utils.py", line 897, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/main.py", line 2994, in completion
    raise exception_type(
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/main.py", line 891, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 520, in get_llm_provider
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 497, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=Ollama
Params: {'model': 'llama3.2', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': None, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, 'raw': None}
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/bin/run_flow", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/src/write_a_book_with_flows/main.py", line 135, in main
    asyncio.run(run_flow())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/src/write_a_book_with_flows/main.py", line 123, in run_flow
    await book_flow.kickoff()
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/flow/flow.py", line 208, in kickoff
    await asyncio.gather(*tasks)
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/flow/flow.py", line 217, in _execute_start_method
    result = await self._execute_method(self._methods[start_method])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/flow/flow.py", line 224, in _execute_method
    else method(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/src/write_a_book_with_flows/main.py", line 42, in generate_book_outline
    .kickoff(inputs={"topic": self.state.topic, "goal": self.state.goal})
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/crew.py", line 493, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/crew.py", line 597, in _run_sequential_process
    return self._execute_tasks(self.tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/crew.py", line 695, in _execute_tasks
    task_output = task.execute_sync(
                  ^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/task.py", line 191, in execute_sync
    return self._execute_core(agent, context, tools)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/task.py", line 247, in _execute_core
    result = agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agent.py", line 240, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agent.py", line 240, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agent.py", line 239, in execute_task
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agent.py", line 228, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 93, in invoke
    formatted_answer = self._invoke_loop()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 175, in _invoke_loop
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 115, in _invoke_loop
    answer = self.llm.call(
             ^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/crewai/llm.py", line 155, in call
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1007, in wrapper
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/utils.py", line 897, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/main.py", line 2994, in completion
    raise exception_type(
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/main.py", line 891, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 520, in get_llm_provider
    raise e
  File "/home/mytest/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 497, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=Ollama
Params: {'model': 'llama3.2', 'format': None, 'options': {'mirostat': None, 'mirostat_eta': None, 'mirostat_tau': None, 'num_ctx': None, 'num_gpu': None, 'num_thread': None, 'num_predict': None, 'repeat_last_n': None, 'repeat_penalty': None, 'temperature': None, 'stop': None, 'tfs_z': None, 'top_k': None, 'top_p': None}, 'system': None, 'template': None, 'keep_alive': None, 'raw': None}
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
An error occurred while running the flow: Command '['uv', 'run', 'run_flow']' returned non-zero exit status 1.

(.venv) mytest@mybox ~/Documents/mycode/2024/crewAI-examples/write_a_book_with_flows $ `

**Comment by imomin** [comment]
With the new  changes made to pyproject.toml, the above steps/solution no longer works.

I updated the crew.py code to use Ollama by importing LLM from crewai and modified `llm=LLM(model="ollama/llama3.1:8b", base_url="http://localhost:11434")`. However, I am still getting below error. The error doesn't give much details to debug/troubleshoot.  Need to have a proper error handling and show which line in the main.py is throwing the error.


_Running the Crew
Traceback (most recent call last):
  File "/Users/macbook/Projects/LLMDemo/storybook/.venv/bin/run_crew", line 5, in <module>
    from storybook.main import run
ImportError: cannot import name 'run' from 'storybook.main' (/Users/macbook/Projects/LLMDemo/storybook/src/storybook/main.py)
An error occurred while running the crew: Command '['uv', 'run', 'run_crew']' returned non-zero exit status 1._

**Comment by CStrue** [comment]
Can you run: crewai flow kickoff

it creates the chapters but does not save the content into the file

**Comment by ps6chopatrick** [comment]
I have the exact same problem trying to replace openai with ollama :
cannot import name 'run' from 'write_a_book_with_flows.main

**Comment by joaomdmoura** [comment]
cc @bhancockio :)

**Comment by imomin** [comment]
I was able to resolve the issue. The error handling is a bit cryptic.  If I recall correctly, I had to make some changes in .toml file and change run = "storybook.main:kickoff" to run_crew = "storybook.main:kickoff". Also, the name of the agent in yaml file has to be same as agent function name in crew. I imported LLM from crewai and initialized Ollama as llm=LLM(model="ollama/llama3.1:8b", base_url="http://localhost:11434")  I hope it helps.

I wish, it threw better errors.

**Comment by bhancockio** [comment]
Hey @bluehose54! Thank you for sharing this issue.

The core issue is that we made some last minute changes to flows to simplify them and make them simpler.

Please checkout the updated version of this example here: https://github.com/crewAIInc/crewAI-examples/tree/main/write_a_book_with_flows

Here are the major changes which will hopefully clear up any confusion.
- We updated the project to use the latest version of crewAI from `0.76.2` to `0.76.9`. 
- In the updated version, we changed the way to kickoff the flow. You will now run `crewai flow kickoff` to start a flow instead of `crewai run`
  - @imomin You were spot on! In the updated toml file, we changed the way to run flows to include a new script like this `kickoff = "write_a_book_with_flows.main:kickoff"`
- We changed the name of the book from `"The Current State of AI in September 2024: Trends Across Industries and What's Next"` to `"The Current State of AI in September 2024"`. On Window's machines, the `:` in the title of the book was causing issues during the saving process.
- We tweaked the way we run the `WriteBookChapterCrew` by using `kickoff` instead of `kickoff_async`

If you have any additional issues with this example, please let us know!

Also, I do apologize for all the confusion around this example.

**Comment by ps6chopatrick** [comment]
It doesn't work for me... After a few hours of effort and many unsuccessful attempts I give up for now...

**Comment by CStrue** [comment]
For me it worked now after pulling the changes, also works now with Ollama

**Comment by ps6chopatrick** [comment]
what is your python version? I'm using 3.11.5

**Comment by CStrue** [comment]
3.12.5

you need to run a git pull to fetch the updates

I also changed the llm configuration to this for using ollama in bothe crew.py files: 

    llm = ChatOpenAI(
            api_key="ollama",
            model="ollama/llama3.1:latest",
            base_url="http://{ip-adress}:11434",
            )

**Comment by ps6chopatrick** [comment]
Thanks for your encouraging answer but the problems remain, for example: the command "poetry lock" generates the message "[tool.poetry] section not found in pyproject.toml". I am then forced to modify and adapt the pyproject.toml to use poetry... It still does not work. I wonder if some steps are missing in the readme.md...

**Comment by CStrue** [comment]
i didn't run "poetry lock"

upgrade crewai toolkit (s. web page)

crewai update
crewai install
crewai flow kickoff

**Comment by bhancockio** [comment]
Thank you for providing all of those suggestions @CStrue. Please follow those steps @ps6chopatrick and let me know if fixes your flow!

**Comment by bhancockio** [comment]
Just updated the README to use the proper kickoff command! Thank you for sharing @ps6chopatrick!

If you swap out models to OpenAI, does the flow work properly?
