### ISSUE TITLE
cache_tools.py", line 26 - list index out of range

### ISSUE THREAD

**Issue by tkunstek** [crewAIInc/crewAI-examples#26]
While running the stock analytics example, I occasionally get this cache error. This might belong in the main github repo.

Action Input: <https://www.fool.com/investing/2024/01/14/apple-stock-time-to-buy-the-dip/>Read and summarize article
Article title: Apple Stock: Time to Buy the Dip? is not a valid tool, try one of [Scrape website content, Search the internet, Search news on the internet, yahoo_finance_news, Search 10-Q form, Search 10-K form, Delegate work to co-worker, Ask question to co-worker, Hit Cache]. Do I need to use a tool? Yes.
Action: Hit Cache
Action Input: <https://www.fool.com/investing/2024/01/14/apple-stock-time-to-buy-the-dip/>Traceback (most recent call last):
  File "/Users/tkunstek/Dev/crew-finance/crewAI-examples/stock_analysis/main.py", line 54, in <module>
    result = financial_crew.run()
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tkunstek/Dev/crew-finance/crewAI-examples/stock_analysis/main.py", line 42, in run
    result = crew.kickoff()
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/crewai/crew.py", line 106, in kickoff
    return self.__sequential_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/crewai/crew.py", line 124, in __sequential_loop
    task_output = task.execute(task_output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/crewai/task.py", line 53, in execute
    result = self.agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/crewai/agent.py", line 120, in execute_task
    return self.agent_executor.invoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain/chains/base.py", line 93, in invoke
    return self(
           ^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain/chains/base.py", line 316, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain/agents/agent.py", line 1312, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain/agents/agent.py", line 1038, in _take_next_step
    [
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain/agents/agent.py", line 1038, in <listcomp>
    [
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/crewai/agents/executor.py", line 111, in _iter_next_step
    observation = tool.run(
                  ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain_core/tools.py", line 365, in run
    raise e
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain_core/tools.py", line 337, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/langchain_core/tools.py", line 514, in _run
    else self.func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/crewai/lib/python3.11/site-packages/crewai/tools/cache_tools.py", line 26, in hit_cache
    tool = split[1].split("|input:")[0].strip()
           ~~~~~^^^
IndexError: list index out of range

**Comment by Biancamazzi** [comment]
Do you still need help with this issue?
